#!/usr/bin/env python3

import argparse  # using two libraries
from mcb185 import *  

# setup
parser = argparse.ArgumentParser(description='Counting letters in a file.')
# required arguments
parser.add_argument('--fasta', required=True, type=str,
	metavar='<str>', help='fasta file')

parser.add_argument('--all', action='store_true',
	help='stats for all files')
# finalization
arg = parser.parse_args()

tcount = {}
for name, seq in read_fasta(arg.fasta):
	count = letterCount(seq)
	print(count, kdCalc(seq)) # put mcb185 because it's not here.